-- DO NOT EDIT THIS FILE DIRECTLY
-- This is a file generated from a literate programing source file located at
-- https://github.com/zzamboni/dot-hammerspoon/blob/master/init.org.
-- You should make any changes there and regenerate it from Emacs org-mode using C-c C-v t

hs.logger.defaultLogLevel="debug"

hs.loadSpoon("SpoonInstall")

-- spoon.SpoonInstall.repos.zzspoons = {
--   url = "https://github.com/zzamboni/zzSpoons",
--   desc = "zzamboni's spoon repository",
-- }

spoon.SpoonInstall.use_syncinstall = true

Install=spoon.SpoonInstall

-- Install:andUse("SendToOmniFocus",
--                {
--                  disable = true,
--                  config = {
--                    quickentrydialog = false,
--                    notifications = false
--                  },
--                  hotkeys = {
--                    send_to_omnifocus = { hyper, "t" }
--                  },
--                  fn = OF_register_additional_apps,
--                }
-- )
--
-- Install:andUse("ColorPicker",
--                {
--                  disable = true,
--                  hotkeys = {
--                    show = { hyper, "z" }
--                  },
--                  config = {
--                    show_in_menubar = false,
--                  },
--                  start = true,
--                }
-- )
--
-- Install:andUse("BrewInfo",
--                {
--                  config = {
--                    brew_info_style = {
--                      textFont = "Inconsolata",
--                      textSize = 14,
--                      radius = 10 }
--                  },
--                  hotkeys = {
--                    -- brew info
--                    show_brew_info = {hyper, "b"},
--                    open_brew_url = {shift_hyper, "b"},
--                    -- brew cask info - not needed anymore, the above now do both
--                    -- show_brew_cask_info = {shift_hyper, "c"},
--                    -- open_brew_cask_url = {hyper, "c"},
--                  }
--                }
-- )

Install:andUse("EjectMenu", {
                 config = {
                   eject_on_lid_close = false,
                   eject_on_sleep = false,
                   show_in_menubar = true,
                   notify = true,
                 },
                 start = true,
                -- loglevel = 'debug'
})

Install:andUse("MicMute",
               {
                 -- start = true,
                 disable = false,
               }
)
